const logos = [
    "bootstrap.svg",
    "bun.svg",
    "c.svg",
    "chartjs.svg",
    "chrome.svg",
    "css.svg",
    "docker.svg",
    "eclipse.svg",
    "embedded c.svg",
    "express.svg",
    "fastapi.svg",
    "flask.svg",
    "gcc.svg",
    "gimp.svg",
    "git.svg",
    "github.svg",
    "github actions.svg",
    "google colab.svg",
    "hibernate.svg",
    "homebrew.svg",
    "html5.svg",
    "java.svg",
    "js.svg",
    "kali.svg",
    "material ui.svg",
    "matplotlib.svg",
    "mysql.svg",
    "nodejs.svg",
    "npm.svg",
    "numpy.svg",
    "pandas.svg",
    "playwright.svg",
    "postman.svg",
    "pycharm.svg",
    "pytest.svg",
    "python.svg",
    "pytorch.svg",
    "r.svg",
    "react.svg",
    "spring.svg",
    "supabase.svg",
    "swift.svg",
    "tailwind.svg",
    "tensorflow.svg",
    "typescript.svg",
    "unity.svg",
    "vim.svg",
    "visual studio.svg",
    "vitejs.svg",
    "vitest.svg",
    "vscode.svg",
    "xcode.svg"
]


